export { default as Dashboard } from './dashboard/Dashboard';
export { default as Categories } from './categories/Categories';
export { default as Login } from './auth/Login';
export { default as Register } from './auth/Register';
export { default as ResetPassword } from './auth/ResetPassword';
export { default as Profile } from './profile/Profile';
export { default as NotFound } from './notFound/NotFound';
export { default as Transactions } from './transactions/Transactions';
export { default as Analytics } from './analytics/Analytics';